### ISSUE TITLE
[Mdl-Popover] BUG TypeError firing onDestroy()

### ISSUE THREAD

**Issue by rarenal** [mseemann/angular2-mdl#1075]
Hello,
I'm using MdlSelect in my project (which includes MdlPopover) and since today I am facing an error whenever I swap from a view with an MdlSelect component to another view, which fires its ngOnDestroy() method causing the next error:
`ERROR Error: Uncaught (in promise): TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.
TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.
    at HTMLElement.proto.(anonymous function) [as removeEventListener] (http://localhost:4200/polyfills.bundle.js:3858:46)
    at MdlPopoverComponent.ngOnDestroy (http://localhost:4200/vendor.bundle.js:57832:39)
    at callProviderLifecycles (http://localhost:4200/vendor.bundle.js:11657:18)
    at callElementProvidersLifecycles (http://localhost:4200/vendor.bundle.js:11626:13) .......`

This error referes to the next method in node_modules/@angular-mdl/popover/popover.js

`MdlPopoverComponent.prototype.ngOnDestroy = function () {
        this.elementRef.nativeElement.removeEventListener('hide');
    };`

The error itself claims that removeEventListener needs 2 arguments instead of one, so I changed it to: 
`MdlPopoverComponent.prototype.ngOnDestroy = function () {
        this.elementRef.nativeElement.removeEventListener('hide', this.hide.bind(this));
    };`
and now it works perfectly, without any error, even I don't know if that would be the proper solution. I'll try to update it, as I need the package to work perfectly.

Thank you

**Comment by rarenal** [comment]
I close this here, as it is not the right place, heading to angular2-mdl-ext.
Im sorry
