### ISSUE TITLE
"Unexpected token import" error with Angular4 + Universal +angular-mdl

### ISSUE THREAD

**Issue by deepakpapola** [mseemann/angular2-mdl#1309]
### the error accur while ssr

/home/dp/Desktop/fernwehsoul copy (copy)/node_modules/@angular-mdl/core/components/dialog-outlet/mdl-dialog-outlet.component.js:1
(function (exports, require, module, __filename, __dirname) { import { Component, ViewContainerRef, forwardRef, Inject } from '@angular/core';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.z45w (/home/dp/Desktop/dist-server/main.bundle.js:1:300052)

### Help!

**Comment by mseemann** [comment]
universal is not supported. if you need this feature feel free to provide a pr.
