### ISSUE TITLE
Unable to compile AOT

### ISSUE THREAD

**Issue by grizzm0** [mseemann/angular2-mdl#165]
I updated to latest angular-cli yesterday (beta 18) and got this error while building AOT. Tried a brand new project and added angular2-mdl to it and got the same result.

I'm not sure if this is related to angular2-mdl or if it's something wrong with latest angular-cli. But the error appears while compiling angular2-mdl. It seems to me like some path is invalid as it's looking for node_modules inside my src folder.

```
 20% building modules 91/197 modules 106 active ...s/dialog/mdl-dialog-host.component.js
 20% building modules 91/199 modules 108 active ...lar/common/src/directives/ng_class.js
 20% building modules 91/202 modules 111 active .../directives/default_value_accessor.jsresolve '../common/append-view-container-ref-directive.ngfactory' in '/Users/Kristofer/Projects/WMS-frontend/src/node_modules/angular2-mdl/components/layout'
  using description file: /Users/Kristofer/Projects/WMS-frontend/package.json (relative path: ./src/node_modules/angular2-mdl/components/layout)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/Kristofer/Projects/WMS-frontend/package.json (relative path: ./src/node_modules/angular2-mdl/components/layout)
    using description file: /Users/Kristofer/Projects/WMS-frontend/package.json (relative path: ./src/node_modules/angular2-mdl/components/common/append-view-container-ref-directive.ngfactory)
      as directory
        /Users/Kristofer/Projects/WMS-frontend/src/node_modules/angular2-mdl/components/common/append-view-container-ref-directive.ngfactory doesn't exist
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/Kristofer/Projects/WMS-frontend/src/node_modules/angular2-mdl/components/common/append-view-container-ref-directive.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /Users/Kristofer/Projects/WMS-frontend/src/node_modules/angular2-mdl/components/common/append-view-container-ref-directive.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/Kristofer/Projects/WMS-frontend/src/node_modules/angular2-mdl/components/common/append-view-container-ref-directive.ngfactory.js doesn't exist

/Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/lib/Compiler.js:220
					if(err) return callback(err);
                    ^
TypeError: Cannot read property 'hash' of undefined
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/angular-cli/tasks/build-webpack.js:35:26
    at Compiler.onCompiled (/Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/lib/Compiler.js:220:21)
    at Compiler.<anonymous> (/Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/lib/Compiler.js:464:19)
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/tapable/lib/Tapable.js:148:11
    at Compilation.<anonymous> (/Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/lib/Compilation.js:443:11)
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/lib/Compilation.js:420:13
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/lib/Compilation.js:332:11
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/node_modules/async/lib/async.js:241:17)
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/lib/Compilation.js:332:11
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/node_modules/async/lib/async.js:241:17)
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/lib/Compilation.js:332:11
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/node_modules/async/lib/async.js:241:17)
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/lib/Compilation.js:332:11
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/node_modules/async/lib/async.js:241:17)
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/lib/Compilation.js:332:11
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/node_modules/async/lib/async.js:241:17)
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at errorAndCallback (/Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/lib/Compilation.js:199:5)
    at errorOrWarningAndCallback (/Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/lib/Compilation.js:228:13)
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/lib/Compilation.js:232:12
    at onDoneResolving (/Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/lib/NormalModuleFactory.js:40:20)
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/lib/NormalModuleFactory.js:117:20
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/node_modules/async/lib/async.js:726:13
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/node_modules/async/lib/async.js:241:17)
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/node_modules/async/lib/async.js:723:17
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/node_modules/async/lib/async.js:167:37
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/webpack/lib/NormalModuleFactory.js:112:22
    at onResolved (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/Resolver.js:70:11)
    at loggingCallbackWrapper (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/Kristofer/Projects/WMS-frontend/node_modules/tapable/lib/Tapable.js:108:46)
    at innerCallback (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/tapable/lib/Tapable.js:210:15
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:39:4
    at loggingCallbackWrapper (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/Kristofer/Projects/WMS-frontend/node_modules/tapable/lib/Tapable.js:108:46)
    at innerCallback (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/tapable/lib/Tapable.js:210:15
    at innerCallback (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/Resolver.js:123:11)
    at loggingCallbackWrapper (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/tapable/lib/Tapable.js:210:15
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:45:5
    at loggingCallbackWrapper (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/Kristofer/Projects/WMS-frontend/node_modules/tapable/lib/Tapable.js:115:11)
    at innerCallback (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/Resolver.js:123:11)
    at loggingCallbackWrapper (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/tapable/lib/Tapable.js:210:15
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:45:5
    at loggingCallbackWrapper (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/Kristofer/Projects/WMS-frontend/node_modules/tapable/lib/Tapable.js:108:46)
    at innerCallback (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/tapable/lib/Tapable.js:210:15
    at afterInnerCallback (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/Kristofer/Projects/WMS-frontend/node_modules/tapable/lib/Tapable.js:108:46)
    at innerCallback (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/tapable/lib/Tapable.js:210:15
    at afterInnerCallback (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/Kristofer/Projects/WMS-frontend/node_modules/tapable/lib/Tapable.js:108:46)
    at innerCallback (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/tapable/lib/Tapable.js:210:15
    at Resolver.<anonymous> (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/FileExistsPlugin.js:23:12)
    at Storage.finished (/Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:39:16)
    at /Users/Kristofer/Projects/WMS-frontend/node_modules/enhanced-resolve/node_modules/graceful-fs/polyfills.js:264:29
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by mseemann** [comment]
just facing the same problem. it's a pain. looks like aot is pre-alpha :(

**Comment by mseemann** [comment]
npm version 2.2.2 should fix this.
