### ISSUE TITLE
Build Issue with angular-cli beta 11 

### ISSUE THREAD

**Issue by agatlin** [mseemann/angular2-mdl#343]
When running `ng build`, `ng build --prod`, or` ng serve`, angular-cli builds just fine with angular2-mdl. However, it fails when building with the `ng build --prod --aot`.

`ng build --prod --aot`

Here is the error message.

```
C:\Projects\ang-cli\fst>ng build --aot
 10% building modules 3/3 modules 0 activecan't resolve module ../common/index from C:/Projects/ang-cli/fst/node_modules/angular2-mdl/components/dialog/index.d.ts
Cannot read property 'MdlCommonsModule' of undefined, resolving symbol MdlDialogModule in C:/Projects/ang-cli/fst/node_modules/angular2-mdl/components/dialog/index.d.ts, resolving symbol MdlDialogModule in C:/Projects/ang-cli/fst/node_modules/angular2-mdl/components/dialog/index.d.ts
Error: Cannot read property 'MdlCommonsModule' of undefined, resolving symbol MdlDialogModule in C:/Projects/ang-cli/fst/node_modules/angular2-mdl/components/dialog/index.d.ts, resolving symbol MdlDialogModule in C:/Projects/ang-cli/fst/node_modules/angular2-mdl/components/dialog/index.d.ts
    at simplifyInContext (C:\Projects\ang-cli\fst\node_modules\@angular\compiler-cli\src\static_reflector.js:475:23)
    at StaticReflector.simplify (C:\Projects\ang-cli\fst\node_modules\@angular\compiler-cli\src\static_reflector.js:478:22)
    at StaticReflector.annotations (C:\Projects\ang-cli\fst\node_modules\@angular\compiler-cli\src\static_reflector.js:60:36)
    at NgModuleResolver.resolve (C:\Projects\ang-cli\fst\node_modules\@angular\compiler\bundles\compiler.umd.js:14261:46)
    at CompileMetadataResolver._loadNgModuleMetadata (C:\Projects\ang-cli\fst\node_modules\@angular\compiler\bundles\compiler.umd.js:14646:45)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (C:\Projects\ang-cli\fst\node_modules\@angular\compiler\bundles\compiler.umd.js:14636:23)
    at addNgModule (C:\Projects\ang-cli\fst\node_modules\@angular\compiler\bundles\compiler.umd.js:12944:43)
    at C:\Projects\ang-cli\fst\node_modules\@angular\compiler\bundles\compiler.umd.js:12957:16
    at Array.forEach (native)
    at _createNgModules (C:\Projects\ang-cli\fst\node_modules\@angular\compiler\bundles\compiler.umd.js:12956:28)
    at analyzeNgModules (C:\Projects\ang-cli\fst\node_modules\@angular\compiler\bundles\compiler.umd.js:12700:16)
    at analyzeAndValidateNgModules (C:\Projects\ang-cli\fst\node_modules\@angular\compiler\bundles\compiler.umd.js:12704:20)
    at OfflineCompiler.compileModules (C:\Projects\ang-cli\fst\node_modules\@angular\compiler\bundles\compiler.umd.js:12775:20)
    at CodeGenerator.codegen (C:\Projects\ang-cli\fst\node_modules\@angular\compiler-cli\src\codegen.js:58:30)
    at C:\Projects\ang-cli\fst\node_modules\@ngtools\webpack\src\plugin.js:210:73
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by mseemann** [comment]
what versions of angular and angular2-mdl you are using?

**Comment by agatlin** [comment]
angular2-mdl: v2.8.0
angular2: v2.3.1

**Comment by agatlin** [comment]
I don't know that matters since it is not showing up in the error, but I do have the lastest version of the two angular2-mdl-ext modules installed as well.

**Comment by mseemann** [comment]
ok, that's up to date. your version of a-cli is a little bit outdated. please consider upgrading to the current version. here is an example project that works with aot: https://github.com/mseemann/a2-mdl-webpack. it uses 1.0.0-beta.22-1. it seems there are some problems with the most current version of angular (https://github.com/angular/angular-cli/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20aot) - so you need to use the 2.2.3 version of angular.

the current version 2.3.1 stated that a lib should be rebuilt (https://github.com/angular/angular/blob/master/CHANGELOG.md) but you error message did not look like your problem. *hm*

angular2-mdl-ext  should not be a problem.

**Comment by agatlin** [comment]
I mistakenly lied. I am using version 1.0.0-beta.22-1 of angular-cli. I will revert angular back down 2.2.3. Thank you so very much. By the way, I really love your angular2-mdl-lite! It is fantastic!

**Comment by mseemann** [comment]
never mind! thx:)
