### ISSUE TITLE
"angular2-mdl": "^2.11.0" giving errors on attempted import in Application module

### ISSUE THREAD

**Issue by st-clair-clarke** [mseemann/angular2-mdl#415]
Hi,
Everytime I import MdlModule in may ApplicationModule, I get the following error:

```
reflection_capabilities.js:58Uncaught TypeError: ctorParameters.map is not a function
    at ReflectionCapabilities.parameters (http://localhost:4200/main.bundle.js:70400:45)
    at Reflector.parameters (http://localhost:4200/main.bundle.js:70534:44)
    at CompileMetadataResolver.getDependenciesMetadata (http://localhost:4200/main.bundle.js:47561:54)
    at CompileMetadataResolver.getTypeMetadata (http://localhost:4200/main.bundle.js:47526:26)
    at CompileMetadataResolver.getDirectiveMetadata (http://localhost:4200/main.bundle.js:47301:28)
    at http://localhost:4200/main.bundle.js:47370:49
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/main.bundle.js:47363:44)
    at http://localhost:4200/main.bundle.js:47351:50
    at Array.forEach (native)```

When I remove the MdlModule import entry, my application runs normal again

I am using  "angular-cli": "^1.0.0-beta.21" in Webstorm for the angular2-app

**Comment by mseemann** [comment]
Please have a look at http://stackoverflow.com/questions/41285889/ctorparameters-map-is-not-a-function-in-angular2-mdl why you see this error and how to solve it.
