### ISSUE TITLE
Universal Support

### ISSUE THREAD

**Issue by sebastianmacias** [mseemann/angular2-mdl#557]
When trying to pre-render routes with Angular Universal. I'm getting errors like this:

`✔ SASS Build Time: 5ms
✔ AoT Build Time: 10.21s
✔ Build time: 3.82s
✔ Optimizing time: 6.06s
--------------------------------------------
app.js (472.808 KB) -> app.js.gz (98.552 KB)
--------------------------------------------
Build: 21138.162ms
--------------------------------------------

> angular-rollup-starter@0.2.1 prerender /home/dev/Tests/angular-rollup-starter
> node ./scripts/index.js --prerender

--------------------------------------------
EXCEPTION: this.rippleContainer.appendChild is not a function
ORIGINAL STACKTRACE:
TypeError: this.rippleContainer.appendChild is not a function
    at MdlButtonRippleDirective.MdlRippleDirective.ngOnChanges (/home/dev/Tests/angular-rollup-starter/node_modules/angular2-mdl/bundle/angular2-mdl.js:818:34)
    at MdlButtonRippleDirective.ngOnChanges (/home/dev/Tests/angular-rollup-starter/node_modules/angular2-mdl/bundle/angular2-mdl.js:832:104)
    at Wrapper_MdlButtonRippleDirective.ngDoCheck (/MdlRippleModule/MdlButtonRippleDirective/wrapper.ngfactory.js:28:18)
    at CompiledTemplate.proxyViewClass.View_AppComponent0.detectChangesInternal (/AppModule/AppComponent/component.ngfactory.js:67:38)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (/home/dev/Tests/angular-rollup-starter/node_modules/@angular/core/bundles/core.umd.js:12208:18)
    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (/home/dev/Tests/angular-rollup-starter/node_modules/@angular/core/bundles/core.umd.js:12193:22)
    at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.detectChangesInternal (/AppModule/AppComponent/host.ngfactory.js:27:19)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (/home/dev/Tests/angular-rollup-starter/node_modules/@angular/core/bundles/core.umd.js:12208:18)
    at ViewRef_.detectChanges (/home/dev/Tests/angular-rollup-starter/node_modules/@angular/core/bundles/core.umd.js:9377:24)
    at /home/dev/Tests/angular-rollup-starter/node_modules/@angular/core/bundles/core.umd.js:8301:71
    at Array.forEach (native)
    at ApplicationRef_.tick (/home/dev/Tests/angular-rollup-starter/node_modules/@angular/core/bundles/core.umd.js:8301:29)
...
...
`
Is support for angular universal planned?

**Comment by mseemann** [comment]
hi. no, it is planned to support angular universal.

**Comment by sebastianmacias** [comment]
Hi @mseemann,  do you mean, you are not planning to support angular universal?

**Comment by mseemann** [comment]
hi. right.

**Comment by mecp** [comment]
Hi @mseemann,

I am getting the same error when using with **universal**.

I am wondering what's the relation here with PR https://github.com/mseemann/angular2-mdl/pull/202, and Issue https://github.com/mseemann/angular2-mdl/issues/168. It seems the idea of supporting universal existed at some point.
